### PR TITLE
Fix #16

### LINKED ISSUE #16: Node does not exist for SceneGroupItemBlock: None
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/remarks/__main__.py", line 151, in <module>
    main()
  File "/app/remarks/__main__.py", line 147, in main
    run_remarks(input_dir, output_dir, **args_dict)
  File "/app/remarks/remarks.py", line 96, in run_remarks
    process_document(metadata_path, out_path, doc_type, **kwargs)
  File "/app/remarks/remarks.py", line 271, in process_document
    (ann_data, has_ann_hl), version = parse_rm_file(ann_rm_file)
  File "/app/remarks/conversion/parsing.py", line 259, in parse_rm_file
    return parse_v6(file_path), "V6"
  File "/app/remarks/conversion/parsing.py", line 128, in parse_v6
    dims = determine_document_dimensions(file_path)
  File "/app/remarks/conversion/parsing.py", line 183, in determine_document_dimensions
    build_tree(tree, blocks)
  File "/app/.venv/lib/python3.10/site-packages/rmscene/scene_stream.py", line 773, in build_tree
    raise ValueError(
    ValueError: Node does not exist for SceneGroupItemBlock: None`
```

```py
def build_tree(tree: SceneTree, blocks: Iterable[Block]):
    for b in block:
        if ...:
            ...
        elif isinstance(b, SceneGroupItemBlock):
            # Add this entry to children of parent_id
            node_id = b.item.value
            # if node_id == None:
                # continue
            if node_id not in tree:
                raise ValueError(
                    "Node does not exist for SceneGroupItemBlock: %s" % node_id
                )
            item = replace(b.item, value=tree[node_id])
            tree.add_item(item, b.parent_id)
```

Given that the value in the `SceneGroupItemBlock` is a `tp.Optional[CrdtId]` it's defined that it's ok to be None?

I added the commented continue if None code and there are no further errors in the document.

Am I correct in assuming it's ok to just skip it if it's None given that the value is optionally typed?

### PR DESCRIPTION
**Pull request by Seb-sti1**
This should fix #16 

As Rick Lupton guessed in the issue `b.item.deleted_length` is non-zero when `node_id` is None.

```json
{
  "CrdtGroupItem": {
    "deletedLength": 1,
    "id": "1:16",
    "left": "0:0",
    "parentId": "0:11",
    "right": "0:0"
  },
  "minVersion": 1,
  "version": 1
}
```

compared to the following when `deletedLength == 0`

```json
{
    "CrdtGroupItem": {
        "deletedLength": 0,
        "id": "0:13",
        "left": "0:0",
        "parentId": "0:1",
        "right": "0:0",
        "value": {
            "nodeId": "0:11"
        }
    },
    "minVersion": 1,
    "version": 1
}
```

It fixes the parsing of my file mentioned in #32 (19 `CrdtGroupItem` where `nodeId == None` and `deletedLength > 0`).

@Azeirah could you test if it fixes it for you too?

### CODE REVIEW

**Comment by ricklupton** [comment]
Thanks for fixing this. Although they should come together, I think it would be better to check for node_id not being None, rather than checking for deleted length -- if that makes sense would you mind changing the test, and adding a line to the change log in the README?

**Comment by Azeirah** [comment]
> This should fix #16
> 
> As Rick Lupton guessed in the issue `b.item.deleted_length` is non-zero when `node_id` is None.
> 
> ```json
> {
>   "CrdtGroupItem": {
>     "deletedLength": 1,
>     "id": "1:16",
>     "left": "0:0",
>     "parentId": "0:11",
>     "right": "0:0"
>   },
>   "minVersion": 1,
>   "version": 1
> }
> ```
> 
> compared to the following when `deletedLength == 0`
> 
> ```json
> {
>     "CrdtGroupItem": {
>         "deletedLength": 0,
>         "id": "0:13",
>         "left": "0:0",
>         "parentId": "0:1",
>         "right": "0:0",
>         "value": {
>             "nodeId": "0:11"
>         }
>     },
>     "minVersion": 1,
>     "version": 1
> }
> ```
> 
> It fixes the parsing of my file mentioned in #32 (19 `CrdtGroupItem` where `nodeId == None` and `deletedLength > 0`).
> 
> @Azeirah could you test if it fixes it for you too?

I don't know what the original file was where the error was happening. But I have error monitoring set-up for a large amount of people using rmscene and remarks together. I am updating the service to rmscene 0.6.0 and will definitely open up a new issue if something unexpected comes up.

**Comment by Seb-sti1** [comment]
> Thanks for fixing this. Although they should come together, I think it would be better to check for node_id not being None, rather than checking for deleted length -- if that makes sense would you mind changing the test, and adding a line to the change log in the README?

Done !

**Comment by ricklupton** [comment]
Thanks!

**Pull request merged**
