### PR TITLE
add new colors and tool

### PR DESCRIPTION
**Pull request by ChenghaoMou**
This should address #30 

A few questions:
- Should I bump the version?
- I had to add a workaround for move_id otherwise it will fail. But I have no idea what that part means.

Added a simple test case with a rm with the following rendering:

CleanShot 2024-10-17 at 19 52 09@2x

### CODE REVIEW

**Comment by Azeirah** [comment]
Beautiful! I think this is more @ricklupton's expertise :)

I think the version can be bumped, yes. In my intuitive opinion it would go from 0.5.0 to 0.6.0, since this would improve support marginally for a new device.

If you have further questions, you can also join the scrybble or ReMarkable Discord(s). There are more enthusiastic people working on this software ecosystem in there! :)

https://discord.com/channels/1290767765803634729/1290767766378381434

**Comment by ChenghaoMou** [comment]
> Beautiful! I think this is more @ricklupton's expertise :)
> 
> I think the version can be bumped, yes. In my intuitive opinion it would go from 0.5.0 to 0.6.0, since this would improve support marginally for a new device.
> 
> If you have further questions, you can also join the scrybble or ReMarkable Discord(s). There are more enthusiastic people working on this software ecosystem in there! :)
> 
> [discord.com/channels/1290767765803634729/1290767766378381434](https://discord.com/channels/1290767765803634729/1290767766378381434)

Thank you! I'd love to join, but the Discord link seems broken?

**Comment by Azeirah** [comment]
> > Beautiful! I think this is more @ricklupton's expertise :)
> > I think the version can be bumped, yes. In my intuitive opinion it would go from 0.5.0 to 0.6.0, since this would improve support marginally for a new device.
> > If you have further questions, you can also join the scrybble or ReMarkable Discord(s). There are more enthusiastic people working on this software ecosystem in there! :)
> > [discord.com/channels/1290767765803634729/1290767766378381434](https://discord.com/channels/1290767765803634729/1290767766378381434)
> 
> Thank you! I'd love to join, but the Discord link seems broken?

https://discord.gg/FjdMf9fM

Sorry, I'm still somewhat new to Discord :x

**Comment by ChenghaoMou** [comment]
A follow-up comment: I think I have an idea about the extra data in those blocks — they are color info, at least part of it, in BGR, or potentially BGRA:

```
...
from rich.console import Console
console = Console()
...

for block in blocks:
    if not isinstance(block, (SceneLineItemBlock, SceneGlyphItemBlock)):
        continue
    if block.extra_data.startswith(b'\xa4\x01') and len(block.extra_data) == 6:
        *_, b, g, r, a = block.extra_data
        console.print(block.item.value.text, style=f"#{r:02x}{g:02x}{b:02x}")
```

**Comment by Azeirah** [comment]
It might be a good idea to read up a little on the hardware specifics of the color eink screens. What color particles are in the device? Your suggestion hypothesizes, blue, green, red and alpha.

**Comment by ChenghaoMou** [comment]
Right now, all the colors are predefined in the menu and therefore can be verified by rendering them using above code:
CleanShot 2024-10-19 at 19 32 46@2x

**Comment by Azeirah** [comment]
🤷‍♀️🤷‍♀️

Lgtm but it's up to @ricklupton

**Comment by ricklupton** [comment]
Thanks @ChenghaoMou for adding this and including the test file. Sorry taken a while to get to it.

It looks like there are some other changes in the new `.rm` files (like the test file you added) that are not fully parsed but that can be a separate issue.

**Comment by ricklupton** [comment]
Released now as v0.6.0

**Pull request merged**
